### ISSUE TITLE
Resolution of background

### ISSUE THREAD

**Issue by getPoland** [Robin1101/WebCraft#1]
You can see the white field? You have to change the resolution in [index.css](https://github.com/Robin1101/WebCraft/blob/master/css/index.css ). 
Its very simple to fix this if you don't know how contact me at at joel@rzepka.online or my team at support@rzepka.online !
![screenshot_45](https://user-images.githubusercontent.com/36799117/37150725-121a3276-22d3-11e8-8f87-832250b471da.png)
-----------------------------------------------

**Comment by Robin1101** [comment]
Thanks for your Comment..
I will fix that in teh next update! :smile:
